name: Run test scripts

on:
  workflow_dispatch:
  schedule:
    # run at every half hour
    - cron: '30 * * * *'

jobs:
  script:
    name: Run script
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9"]
        file: [
          "any_element_barmbek_nord",
          "any_element_carabanchel",
          "any_route_barmbek_nord",
          "any_route_carabanchel",
        ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Install dependencies & library
        run: poetry install --all-extras --no-interaction

      - name: Run script
        run: |
          source .venv/bin/activate
          python -m test.scripts.${{ matrix.file }}
