# Run tests with combinations of major dependency releases.
#
# For numpy, the C API version matters:
# https://github.com/numpy/numpy/blob/main/numpy/core/code_generators/cversions.txt

name: Test different dependency versions

on:
  # quite a few jobs, so let's not run this on every push
  workflow_dispatch:
  schedule:
    # run once a day at 12:00 UTC
    - cron: '0 12 * * *'
    
jobs:
  test:
    name: Test dependency combination
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Using 3*4*4=48 out of the maximum 256 jobs
        python: ["3.9", "3.10", "3.11"]
        aiohttp: ["3.8"]
        joblib: ["1.3"]
        networkx: ["2.7", "2.8", "3.0", "3.1"]
        numpy: ["1.23", "1.24", "1.25", "1.26"]
        shapely: ["2.0"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Add different dependency versions
        run: |
          source .venv/bin/activate
          poetry add aiohttp=~${{ matrix.aiohttp }} --python="<=${{ matrix.python }}"
          poetry add joblib=~${{ matrix.joblib }} --python="<=${{ matrix.python }}"
          poetry add networkx=~${{ matrix.networkx }} --python="<=${{ matrix.python }}"
          poetry add shapely=~${{ matrix.shapely }} --python="<=${{ matrix.python }}"
          poetry add numpy=~${{ matrix.numpy }} --python="<=${{ matrix.python }}"

      - name: Install dependencies & library
        run: poetry install --all-extras --no-interaction

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest -vv
